apiVersion: v1
kind: ConfigMap
metadata:
  name: lab7-config
data:
  theme: "dark-mode"
---
apiVersion: v1
kind: Secret
metadata:
  name: lab7-secret
type: Opaque
data:
  # Base64 for 'supersecret'
  api-key: c3VwZXJzZWNyZXQ= 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab7-configured-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configured
  template:
    metadata:
      labels:
        app: configured
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        env:
          # Consuming ConfigMap
          - name: APP_THEME
            valueFrom:
              configMapKeyRef:
                name: lab7-config
                key: theme
          # Consuming Secret
          - name: APP_API_KEY
            valueFrom:
              secretKeyRef:
                name: lab7-secret
                key: api-key
